! Put your rules here in the format:
! old_biome > new_biome
! #minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert

! The # indicates a biome tag/group rather than a single biome:
! #terralith:skylands > null

  terralith:skylands_winter > null
  terralith:skylands_summer > null
  terralith:skylands_autumn > null

  biomesoplenty:lush_savanna > null
  biomesoplenty:end_corruption > null
  biomesoplenty:grassland > null
  biomesoplenty:wasteland > null
  biomesoplenty:tundra > null
  biomesoplenty:cold_desert > null
  
  !ONLY FOR -2k -> 2k
  biomesoplenty:overgrown_greens > minecraft:desert

  biomeswevegone:cika_woods > null
  biomeswevegone:howling_peaks > null
  biomeswevegone:pumpkin_valley > null
  
