! Put your rules here in the format:
! old_biome > new_biome

! The # indicates a biome tag/group rather than a single biome:
! #terralith:skylands > null

! A line that starts with "!" is ignored by the program.


! ----------------------------------- TERRALITH

  terralith:gravel_desert > terralith:wintry_lowlands
  terralith:ice_marsh > terralith:wintry_forest
  terralith:arid_highlands > null

! ----------------------------------- BIOMES O PLENTY

  biomesoplenty:lush_savanna > biomeswevegone:amaranth_grassland
  biomesoplenty:dryland > terralith:alpine_highlands
  biomesoplenty:cold_desert > null
  biomesoplenty:old_growth_dead_forest > null
  biomesoplenty:tundra > terralith:blooming_valley
  biomesoplenty:grassland > terralith:lavender_valley

  biomesoplenty:end_corruption > null

! ----------------------------------- BIOMES WE'VE GONE

  biomeswevegone:dead_sea > null
  biomeswevegone:dacite_ridges > null
  biomeswevegone:basalt_barrera > null