! Put your rules here in the format:
! old_biome > new_biome

! The # indicates a biome tag/group rather than a single biome:
! #terralith:skylands > null

! A line that starts with "!" is ignored by the program.

! ----------------------------------- SAFEZONE FINE-TUNING

  terralith:arid_highlands > biomesoplenty:seasonal_forest
  terralith:steppe > minecraft:cherry_grove

  terralith:highlands > null
  terralith:savanna_badlands > null
  terralith:shrubland > null
  terralith:hot_shrubland > null
  terralith:brushland > null

  terralith:volcanic_peaks > null
  terralith:volcanic_crater > null
  terralith:basalt_cliffs > null

  minecraft:savanna > null

! ----------------------------------- MINECRAFT

  minecraft:birch_forest > terralith:birch_taiga
  minecraft:badlands > terralith:red_oasis
  minecraft:wooded_badlands > terralith:desert_canyon
  minecraft:desert > terralith:desert_spires
  minecraft:frozen_ocean > minecraft:cold_ocean
  minecraft:deep_frozen_ocean > minecraft:deep_cold_ocean

! ----------------------------------- TERRALITH


  terralith:haze_mountain > terralith:cloud_forest
  terralith:rocky_shrubland > terralith:snowy_maple_forest 
  terralith:lush_desert > terralith:desert_spires
  terralith:cold_shrubland > terralith:birch_taiga
  terralith:gravel_desert > terralith:wintry_lowlands
  terralith:ice_marsh > terralith:wintry_forest
  terralith:white_mesa > terralith:red_oasis
  terralith:warped_mesa > terralith:desert_spires
  terralith:scarlet_mountains > terralith:snowy_cherry_grove
  terralith:shield_clearing > terralith:yosemite_lowlands
  terralith:stony_spires > terralith:alpine_highlands
  terralith:temperate_highlands > terralith:lush_valley
  terralith:alpha_islands_winter > terralith:mirage_isles 
  terralith:alpha_islands > terralith:mirage_isles

  terralith:skylands_winter > null
  terralith:skylands_summer > null
  terralith:skylands_autumn > null

! ----------------------------------- BIOMES O PLENTY

  biomesoplenty:lush_savanna > biomeswevegone:amaranth_grassland
  biomesoplenty:grassland > terralith:lavender_valley
  biomesoplenty:tundra > terralith:blooming_valley
  biomesoplenty:pasture > terralith:moonlight_grove 
  biomesoplenty:dryland > terralith:alpine_highlands
  biomesoplenty:fungal_jungle > terralith:tropical_jungle
  biomesoplenty:jade_cliffs > terralith:sakura_grove
  biomesoplenty:marsh > terralith:orchid_swamp
  biomesoplenty:lush_desert > terralith:desert_spires
  biomesoplenty:origin_valley > terralith:moonlight_grove
  biomesoplenty:volcanic_plains > terralith:sandstone_valley 
  biomesoplenty:wasteland > terralith:lush_desert 
  biomesoplenty:wintry_origin_valley > null
  biomesoplenty:pumpkin_patch > null
  biomesoplenty:cold_desert > null
  biomesoplenty:old_growth_dead_forest > null

  biomesoplenty:end_corruption > null

! ----------------------------------- BIOMES WE'VE GONE

  biomeswevegone:prairie > terralith:lavender_forest
  biomeswevegone:windswept_desert > terralith:sandstone_valley
  biomeswevegone:tropical_rainforest > biomeswevegone:crag_gardens
  biomeswevegone:red_rock_peaks > terralith:bryce_canyon
  biomeswevegone:basalt_barrera > terralith:blooming_valley
  biomeswevegone:dacite_ridges > terralith:cloud_forest

  biomeswevegone:dead_sea > null
  biomeswevegone:pumpkin_valley > null
  biomeswevegone:sierra_badlands > null
  biomeswevegone:shattered_glacier > null


