const blacklist = [
  /diagonal.+:.+/, // Diagonal blocks don't like having a tag added

  'minecraft:dirt',
  'minecraft:coarse_dirt',
  'minecraft:rooted_dirt',
  'minecraft:podzol',
  'minecraft:mycelium',
  'minecraft:sand',
  'minecraft:red_sand',
  'minecraft:grass_block',
  'minecraft:snow_block',
  'minecraft:stone',
  'minecraft:netherrack',
  'minecraft:deepslate',
  'minecraft:skulk',
  'minecraft:end_stone',
  'minecraft:ice',
  'minecraft:packed_ice',
  'minecraft:bedrock',
  'minecraft:soul_sand',
  'minecraft:soul_soil',
  'minecraft:basalt',
  'minecraft:smooth_basalt',
  'minecraft:nether_bricks',
  'minecraft:warped_nylium',
  'minecraft:crimson_nylium',
  'minecraft:snow',
  'minecraft:water',
  'minecraft:lava',
  'minecraft:gravel',
  'minecraft:leaf_litter',
  'minecraft:dripstone_block',
  'minecraft:andesite',
  'minecraft:tuff',
  'minecraft:granite',
  'minecraft:diorite',
  'minecraft:calcite',
  'minecraft:blackstone',
  'minecraft:magma_block',
  'minecraft:clay',
  'minecraft:moss_block',
  'minecraft:bamboo',
  'minecraft:fire',
  'minecraft:deepslate',
  'minecraft:cobbled_deepslate',
  'galosphere:lichen_moss',
  'yungscavebiomes:ancient_sand',
  'biomesoplenty:brimstone',
  'biomesoplenty:brimstone_bud',
  'biomesoplenty:bramble',
  'biomesoplenty:rose_quartz_cluster',
  'biomeswevegone:overgrown_stone',
  'biomeswevegone:rocky_stone',
  'create:scoria',
  'create:scorchia',
  'supplementaries:ash',
  
  /.+grass/,
  /.+leaves.*/,
  /.+fern/,
  /.+sprout.*/,
  /minecraft:(?!.*glazed).*terracotta/,
  /biomesoplenty:.*lavender/,
  /biomesoplenty:.+rose_quartz_bud/,
  /biomesoplenty:blackstone_.+/,
  /biomeswevegone:.*allium(?!_petal_block).*/
]

ServerEvents.tags('block', event => {
  event.add('via_romana:path_block', /.*/)
  event.remove('via_romana:path_block', blacklist)
})