version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = false
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
cinchsmissingblocks = true
azurelib = true
everycomp = true
mcwfences = true
farmersdelight = true
upgrade_aquatic = true
alexsmobs = true
storagedelight = true
ribbits = true
oceansdelight = true
galosphere = true
cataclysm = true
another_furniture = true
friendsandfoes = true
irons_spellbooks = true
veggiesdelight = true
dramaticdoors = true
diagonalwalls = true
comforts = true
citadel = true
ends_delight = true
plushie_buddies = true
mcwpaths = true
mcwbridges = true
randomium = true
mcwtrpdoors = true
amendments = true
chisel = true
mynethersdelight = true
handcrafted = true
immersiveores = true
diagonalfences = true
advancednetherite = true
moonlight = true
lookinsharp = true
biomesoplenty = true
sophisticatedbackpacks = true
hybrid-aquatic = true
supplementaries = true
portablehole = true
suppsquared = true
deeperdarker = true
create = true
adorablehamsterpets = true
yungscavebiomes = true
end_villager_trader = true
aquaculture = true
gravestone = true
cluttered = true
biomeswevegone = true
enigmaticlegacyplus = true
architects_palette = true
minecraft = true
lootr = true
iceandfire = true
sophisticatedstorage = true
aquaculturedelight = true
creeperoverhaul = true
waystones = true
decorative_blocks = true
diagonalwindows = true
via_romana = true
toms_storage = true
rechiseled = true
